@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"name": "Caio Rosa",
	"email": "dev.caiorosa@gmail.com",
	"password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "dev.caiorosa@gmail.com",
	"password": "123456"
}

###

# @name create_member
POST {{baseUrl}}/members
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "fullName": "medir amdar",
    "gender_id": 1,
    "dateOfBirth": "2015-01-01T00:00:00",
    "nationality_id": 1,
    "placeOfBirth": "Porto",
    "contact": "912345678",
    "email": "ma@hotmail.com",
    "modality_id": 1,
    "frequency_id": 1,
    "memberType_id": 1,
    "paymentFrequency_id": 1,
    "termsAndConditions": true,
    "healthDeclaration": true,
    "createdBy": "e897a729-2946-4cb7-aea7-fb33c8de8a18",
    "identityDocument": {
        "identityDocumentType_id": 1,
        "identificationNumber": "123456789",
        "expireDate": "2020-01-01T00:00:00",
        "taxIdentificationNumber": "111111111"
    },
    "address": {
        "address": "Rua das Flores",
        "city": "Porto",
        "county": "Porto",
        "parish": "Porto",
        "postalCode": "4000-000"
    },
		"guardian": {
			"fullName": "Jane Doe",
        "relationshipDegree_id": 1,
        "contact": "912345678",
        "address": "Rua das Flores",
        "city": "Porto",
        "county": "Porto",
        "parish": "Porto",
        "postalCode": "4000-000"
		}
}

###

# @name fetch_recent_members
GET {{baseUrl}}/members
Content-Type: application/json
Authorization: Bearer {{authToken}}