@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"name": "Caio Rosa",
	"email": "dev.caiorosa@gmail.com",
	"password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email": "dev.caiorosa@gmail.com",
	"password": "123456"
}

###

# @name create_member
POST {{baseUrl}}/members
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "fullName": "Daniel José Batista Paiva",
    "genderId": 1,
    "dateOfBirth": "2018-01-04T00:00:00.000Z",
    "nationalityId": 1,
    "placeOfBirth": "Foros de Salvaterra",
    "email": "patricia81batista1@gmail.com",
    "contact": "918451878",
    "Address": {
        "address": "Rua da liberdade Nº 2",
        "postalCode": "2120179",
        "city": "Foros de Salvaterra",
        "county": "Foros de Salvaterra",
        "parish": "Salvaterra de Magos"
    },
    "IdentityDocument": {
        "identityDocumentTypeId": 1,
        "identificationNumber": "32116212",
        "expireDate": "2028-01-23T23:00:00.000Z",
        "taxIdentificationNumber": "293965676"
    },
    "Guardian": {
        "fullName": "Patricia Alexandra da Costa Batista",
        "contact": "918451878",
        "relationshipDegreeId": 1,
        "address": "Rua da liberdade Nº 2",
        "city": "Foros de Salvaterra",
        "county": "Foros de Salvaterra",
        "parish": "Salvaterra de Magos",
        "postalCode": "2120179"
    },
    "modalityId": 1,
    "frequencyId": 1,
    "memberTypeId": 1,
    "paymentFrequencyId": 1,
    "termsAndConditions": true,
    "healthDeclaration": true
}

###

# @name fetch_recent_members
GET {{baseUrl}}/members
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_payment
POST {{baseUrl}}/member/payment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "memberId": "3f49bade-fcb9-466d-bd1d-bee911df9962",
    "paymentType": "Cota mensal",
    "paymentMethod": "Dinheiro",
    "paymentAmount": 35,
    "paymentDate": "2023-12-26T00:00:00.000Z"
}

###

# @name fetch_payments
GET {{baseUrl}}/members/payments/1/2024
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name create_payment_receipt
POST {{baseUrl}}/payment/receipts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "paymentId": "05ddabef-5aa2-48aa-83a5-ae52b9d888ad",
    "receiptTaxDescription": "Insento Artigo 9.º do CIVA (Ou similar)",
    "receiptTaxPercentage": 0
}
###